settings:
  player-radius: 10 # default: 10 radius
  interval: 2 # default: 2 seconds

blacklist:
  disable: false
  materials:
    - "DIAMOND_BLOCK"

messages:
  prefix: "&8[&4&lDETECTED&8] &c"
  not-allowed-block: "&cYou're not allowed to place an illegal block."
  not-allowed-item: "&cYou're not allowed to use an illegal item."
  detected-block: "Found an illegal block&4(%block%) &cat &4%x%&c, &4%y%&c, &4%z% &cthrough &4%player%&c!"
  detected-item: "Found an illegal item&4(%item%) &cthrough &4%player% &cinventory!"
